apiVersion: v1
kind: Pod
metadata:
  name: dump-stager
spec:
  restartPolicy: Never
  containers:
    - name: stager
      image: alpine:3.20
      command: ["/bin/sh","-lc"]
      args:
        - |
          set -euo pipefail

          echo "Staging Postgres dump into shared PVC..."
          echo "Source file:"
          ls -lh /input/db.dump

          cp -f /input/db.dump /dumps/db.dump
          sync

          echo "Dump staged successfully:"
          ls -lh /dumps/db.dump
      volumeMounts:
        # Shared PVC where the dump will be stored
        - name: dumps
          mountPath: /dumps

        # This is where the dump already exists.
        # In the real setup this could be:
        # - baked into the image
        # - another PVC
        # - an init container output
        - name: input
          mountPath: /input

  volumes:
    - name: dumps
      persistentVolumeClaim:
        claimName: pg-dumps

    # Placeholder volume for the source dump.
    # Replace this with the real source mechanism if needed.
    - name: input
      emptyDir: {}
