apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-restore-job
  labels:
    app: postgres-restore
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 3600  # Keep job for 1 hour after completion
  template:
    metadata:
      labels:
        app: postgres-restore
    spec:
      restartPolicy: Never
      containers:
      - name: restore
        image: ${OKTETO_BUILD_RESTORE_JOB_IMAGE}
        env:
        - name: PGHOST
          value: "main-dev-db"
        - name: PGPORT
          value: "5432"
        - name: PGUSER
          value: "postgres"
        - name: PGDATABASE
          valueFrom:
            configMapKeyRef:
              name: postgres-restore-config
              key: TARGET_DB
        - name: DUMP_PATH_IN_PG_POD
          value: "/var/lib/postgresql/data/pg_dump.sql"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1
            memory: 2Gi
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: main-dev-data
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-restore-config
data:
  TARGET_DB: ${TARGET_DB}
